### ISSUE TITLE
 TypeError: Cannot call method 'trim' of null

### ISSUE THREAD

**Issue by tuncaybahadir** [wuchengwei/node-wget#10]
Hello,
Sometimes I get the following error when downloading content. What can I do about this? After receiving the error in addition it does not give error when I try to download the content again.

SocketF061-15 (err): Missing error handler on `socket`.
SocketF061-15 (err): TypeError: Cannot call method 'trim' of null
SocketF061-15 (err):     at cleanProtocol (/root/node_modules/wget/lib/wget.js:154:16)
SocketF061-15 (err):     at Object.download (/root/node_modules/wget/lib/wget.js:21:23)
SocketF061-15 (err):     at Object.selFing.downloadVideo (/root/nodejs/core/indexSocket.js:102:23)
SocketF061-15 (err):     at Socket.<anonymous> (/root/nodejs/socket/socketRelease.js:180:13)
SocketF061-15 (err):     at Socket.EventEmitter.emit (events.js:106:17)
SocketF061-15 (err):     at Socket.onevent (/root/node_modules/socket.io/lib/socket.js:330:8)
SocketF061-15 (err):     at Socket.onpacket (/root/node_modules/socket.io/lib/socket.js:290:12)
SocketF061-15 (err):     at Client.ondecoded (/root/node_modules/socket.io/lib/client.js:193:14)
SocketF061-15 (err):     at Decoder.Emitter.emit (/root/node_modules/socket.io/node_modules/socket.io-parser/node_modules/component-emitter/index.js:134:20)
SocketF061-15 (err):     at Decoder.add (/root/node_modules/socket.io/node_modules/socket.io-parser/index.js:247:12)

**Comment by devanp92** [comment]
I am having the same issue. Has there been a workaround for this issue?

**Comment by tuncaybahadir** [comment]
Unfortunately, the same way I receive an error

**Comment by tuncaybahadir** [comment]
Does anyone know anything about it ?
